### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by DigTron** [yacoob/aib2ofx#20]
You sir (or mam) are just to god-damn awesome! It would almost be unfair to the rest of us, having all that awesome, releasing and maintaining this for 5 years! I honest to god fist pumped the air when I stumbled in here. One step closer to automated entry of transactions.  Search high and low, and eventually you will find that some legend has already worked it all out for you. Thank you!

ps haven't even looked at it or tried using it yet, just gleamed over it and couldn't help stopping to thank you.

**Comment by yacoob** [comment]
Thanks for the kind words - I had other people helping me out too, especially around PDF conversion. Check whether it works for you, and be sure to report any problems. I'm using the non-PDF OFX generation every week, so usual if it's broken as a result of online interface changing, I end up fixing it within a week :D
